version: "3.7"
services:
  authenticator:
    image: authenticator
    build:
      context: authenticator
      args:
        AUTHENTICATOR_JAR: build/libs/authenticator.jar
        JACOCO_AGENT_JAR: build/libs/jacocoagent.jar
    depends_on:
      - authenticator-db
    command: ["authenticator-db:5432"]
  authenticator-db:
    image: postgres:12.1-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: authenticator
    ports:
      - 5434:5432
  tracker:
    image: tracker
    build:
      context: tracker
      args:
        TRACKER_JAR: build/libs/tracker.jar
        JACOCO_AGENT_JAR: build/libs/jacocoagent.jar
    depends_on:
      - tracker-db
      - mq
    command: ["tracker-db:5432", "mq:5672"]
  tracker-db:
    image: postgres:12.1-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tracker
    ports:
      - 5433:5432
  reporter:
    image: reporter
    build:
      context: reporter
      args:
        REPORTER_JAR: build/libs/reporter.jar
        JACOCO_AGENT_JAR: build/libs/jacocoagent.jar
    depends_on:
      - reporter-db
      - mq
    command: ["reporter-db:27017", "mq:5672"]
  reporter-db:
    image: mongo:4.0.15
    ports:
      - 27018:27017
  mq:
    image: rabbitmq:3.7.16-alpine
    ports:
      - 5673:5672
  nginx:
    image: nginx:1.17.8-alpine
    ports:
      - 8080:80
    volumes:
      - ./nginx-config:/etc/nginx/conf.d
    depends_on:
      - reporter
      - tracker