version: "3.7"
services:
  tracker:
    build:
      context: tracker
      args:
        TRACKER_JAR: build/libs/tracker.jar
    ports:
      - 8080:8080
    depends_on:
      - tracker-db
      - mq
  tracker-db:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tracker
    ports:
      - 5433:5432
  reporter:
    build:
      context: reporter
      args:
        REPORTER_JAR: build/libs/reporter.jar
    ports:
      - 8081:8080
    depends_on:
      - reporter-db
      - mq
  reporter-db:
    image: mongo:4.0.10
    ports:
      - 27018:27017
  mq:
    image: rabbitmq:3.7.16-alpine
    ports:
      - 5673:5672